ver 10.20

diff --git a/RunTest b/RunTest
--- a/RunTest
+++ b/RunTest
@@ -5,15 +5,15 @@
 # selected, depending on which build-time options were used.
 #
 # When JIT support is available, all appropriate tests are run with and without
-# JIT, unless "nojit" is given on the command line. There are also two tests
+# JIT, unless "-nojit" is given on the command line. There are also two tests
 # for JIT-specific features, one to be run when JIT support is available
-# (unless "nojit" is specified), and one when it is not.
+# (unless "-nojit" is specified), and one when it is not.
 #
 # Whichever of the 8-, 16- and 32-bit libraries exist are tested. It is also
 # possible to select which to test by giving "-8", "-16" or "-32" on the
 # command line.
 #
-# As well as "nojit", "-8", "-16", and "-32", arguments for this script are
+# As well as "-nojit", "-8", "-16", and "-32", arguments for this script are
 # individual test numbers, ranges of tests such as 3-6 or 3- (meaning 3 to the
 # end), or a number preceded by ~ to exclude a test. For example, "3-15 ~10"
 # runs tests 3 to 15, excluding test 10, and just "~10" runs all the tests
@@ -24,17 +24,21 @@
 # example, if JIT support is not compiled, test 16 is skipped, whereas if JIT
 # support is compiled, test 15 is skipped.
 #
-# Other arguments can be one of the words "valgrind", "valgrind-log", or "sim"
-# followed by an argument to run cross-compiled executables under a simulator,
-# for example:
+# Other arguments can be one of the words "-valgrind", "-valgrind-log", or
+# "-sim" followed by an argument to run cross-compiled executables under a
+# simulator, for example:
 #
-# RunTest 3 sim "qemu-arm -s 8388608"
+# RunTest 3 -sim "qemu-arm -s 8388608"
+#
+# For backwards compatibility, -nojit, -valgrind, -valgrind-log, and -sim may
+# be given without the leading "-" character.
 #
 # There are two special cases where only one argument is allowed:
 #
 # If the first and only argument is "ebcdic", the script runs the special
 # EBCDIC test that can be useful for checking certain EBCDIC features, even
-# when run in an ASCII environment.
+# when run in an ASCII environment. PCRE2 must be built with EBCDIC support for
+# this test to be run.
 #
 # If the script is obeyed as "RunTest list", a list of available tests is
 # output, but none of them are run.
@@ -65,6 +69,7 @@ title15="Test 15: JIT-specific features when JIT is not available"
 title16="Test 16: JIT-specific features when JIT is available"
 title17="Test 17: Tests of the POSIX interface, excluding UTF/UCP"
 title18="Test 18: Tests of the POSIX interface with UTF/UCP"
+title19="Test 19: Serialization tests"
 maxtest=18
 
 if [ $# -eq 1 -a "$1" = "list" ]; then
@@ -87,6 +92,7 @@ if [ $# -eq 1 -a "$1" = "list" ]; then
   echo $title16
   echo $title17
   echo $title18
+  echo $title19
   exit 0
 fi
 
@@ -207,6 +213,7 @@ do15=no
 do16=no
 do17=no
 do18=no
+do19=no
 
 while [ $# -gt 0 ] ; do
   case $1 in
@@ -229,13 +236,14 @@ while [ $# -gt 0 ] ; do
    16) do16=yes;;
    17) do17=yes;;
    18) do18=yes;;
+   19) do19=yes;;
    -8) arg8=yes;;
   -16) arg16=yes;;
   -32) arg32=yes;;
-   nojit) nojit=yes;;
-   sim) shift; sim=$1;;
-   valgrind) valgrind="valgrind --tool=memcheck -q --smc-check=all";;
-   valgrind-log) valgrind="valgrind --tool=memcheck --num-callers=30 --leak-check=no --error-limit=no --smc-check=all --log-file=report.%p ";;
+   nojit|-nojit) nojit=yes;;
+   sim|-sim) shift; sim=$1;;
+   valgrind|-valgrind) valgrind="valgrind --tool=memcheck -q --smc-check=all";;
+   valgrind-log|-valgrind-log) valgrind="valgrind --tool=memcheck --num-callers=30 --leak-check=no --error-limit=no --smc-check=all --log-file=report.%p ";;
    ~*)
      if expr "$1" : '~[0-9][0-9]*$' >/dev/null; then
        skip="$skip `expr "$1" : '~\([0-9]*\)*$'`"
@@ -364,7 +372,7 @@ if [ $do0  = no -a $do1  = no -a $do2  = no -a $do3  = no -a \
      $do4  = no -a $do5  = no -a $do6  = no -a $do7  = no -a \
      $do8  = no -a $do9  = no -a $do10 = no -a $do11 = no -a \
      $do12 = no -a $do13 = no -a $do14 = no -a $do15 = no -a \
-     $do16 = no -a $do17 = no -a $do18 = no \
+     $do16 = no -a $do17 = no -a $do18 = no -a $do19 = no \
    ]; then
   do0=yes
   do1=yes
@@ -385,6 +393,7 @@ if [ $do0  = no -a $do1  = no -a $do2  = no -a $do3  = no -a \
   do16=yes
   do17=yes
   do18=yes
+  do19=yes
 fi
 
 # Handle any explicit skips at this stage, so that an argument list may consist
@@ -454,45 +463,47 @@ for bmode in "$test8" "$test16" "$test32"; do
     done
   fi
 
-  # Locale-specific tests, provided that either the "fr_FR" or the "french"
-  # locale is available. The former is the Unix-like standard; the latter is
-  # for Windows. Another possibility is "fr". Unfortunately, different versions
-  # of the French locale give different outputs for some items. This test passes
-  # if the output matches any one of the alternative output files.
+  # Locale-specific tests, provided that either the "fr_FR", "fr_CA", "french"
+  # or "fr" locale is available. The first two are Unix-like standards; the
+  # last two are for Windows. Unfortunately, different versions of the French
+  # locale give different outputs for some items. This test passes if the
+  # output matches any one of the alternative output files.
 
   if [ $do3 = yes ] ; then
-    locale -a | grep '^fr_FR$' >/dev/null
-    if [ $? -eq 0 ] ; then
-      locale=fr_FR
-      infile=$testdata/testinput3
-      outfile=$testdata/testoutput3
-      outfile2=$testdata/testoutput3A
-      outfile3=$testdata/testoutput3B
-    else
-      infile=test3input
-      outfile=test3output
-      outfile2=test3outputA
-      outfile3=test3outputB
-      locale -a | grep '^french$' >/dev/null
+    locale=
+
+    # In some environments locales that are listed by the "locale -a"
+    # command do not seem to work with setlocale(). Therefore, we do
+    # a preliminary test to see if pcre2test can set one before going
+    # on to use it.
+
+    for loc in 'fr_FR' 'french' 'fr' 'fr_CA'; do
+      locale -a | grep "^$loc\$" >/dev/null
       if [ $? -eq 0 ] ; then
-        locale=french
-        sed 's/fr_FR/french/' $testdata/testinput3 >test3input
-        sed 's/fr_FR/french/' $testdata/testoutput3 >test3output
-        sed 's/fr_FR/french/' $testdata/testoutput3A >test3outputA
-        sed 's/fr_FR/french/' $testdata/testoutput3B >test3outputB
-      else
-        locale -a | grep '^fr$' >/dev/null
-        if [ $? -eq 0 ] ; then
-          locale=fr
-          sed 's/fr_FR/fr/' $testdata/intestinput3 >test3input
-          sed 's/fr_FR/fr/' $testdata/intestoutput3 >test3output
-          sed 's/fr_FR/fr/' $testdata/intestoutput3A >test3outputA
-          sed 's/fr_FR/fr/' $testdata/intestoutput3B >test3outputB
-        else
-          locale=
+        echo "/a/locale=$loc" | \
+          $sim $valgrind ./pcre2test -q $bmode | \
+            grep "Failed to set locale" >/dev/null
+        if [ $? -ne 0 ] ; then
+          locale=$loc
+          if [ "$locale" = "fr_FR" ] ; then
+            infile=$testdata/testinput3
+            outfile=$testdata/testoutput3
+            outfile2=$testdata/testoutput3A
+            outfile3=$testdata/testoutput3B
+          else
+            infile=test3input
+            outfile=test3output
+            outfile2=test3outputA
+            outfile3=test3outputB
+            sed "s/fr_FR/$loc/" $testdata/testinput3 >test3input
+            sed "s/fr_FR/$loc/" $testdata/testoutput3 >test3output
+            sed "s/fr_FR/$loc/" $testdata/testoutput3A >test3outputA
+            sed "s/fr_FR/$loc/" $testdata/testoutput3B >test3outputB
+          fi
+          break
         fi
       fi
-    fi
+    done
 
     if [ "$locale" != "" ] ; then
       echo $title3 "(using '$locale' locale)"
@@ -519,9 +530,9 @@ for bmode in "$test8" "$test16" "$test32"; do
         fi
       done
     else
-      echo "Cannot test locale-specific features - none of the 'fr_FR', 'fr' or"
-      echo "'french' locales exist, or the \"locale\" command is not available"
-      echo "to check for them."
+      echo "Cannot test locale-specific features - none of the 'fr_FR', 'fr_CA',"
+      echo "'fr' or 'french' locales can be set, or the \"locale\" command is"
+      echo "not available to check for them."
       echo " "
     fi
   fi
@@ -688,7 +699,7 @@ for bmode in "$test8" "$test16" "$test32"; do
   if [ $do16 = yes ] ; then
     echo $title16
     if [ $jit -eq 0 -o "$nojit" = "yes" ] ; then
-      echo "  Skipped because JIT is not available or not usable"
+      echo "  Skipped because JIT is not available or nojit was specified"
     else
       $sim $valgrind ./pcre2test -q $bmode $testdata/testinput16 testtry
       checkresult $? 16 ""
@@ -721,10 +732,18 @@ for bmode in "$test8" "$test16" "$test32"; do
     fi
   fi
 
+  # Serialization tests
+
+  if [ $do19 = yes ] ; then
+    echo $title19
+    $sim $valgrind ./pcre2test -q $bmode $testdata/testinput19 testtry
+    checkresult $? 19 ""
+  fi
+
 # End of loop for 8/16/32-bit tests
 done
 
 # Clean up local working files
-rm -f testSinput test3input test3output test3outputA test3outputB teststdout testtry
+rm -f testSinput test3input testsaved1 testsaved2 test3output test3outputA test3outputB teststdout teststderr testtry
 
 # End
